In [1]:
import numpy as np
import torch

In [3]:
torch.has_mps

True

In [2]:
torch.cuda.is_available()

True

In [3]:
torch.cuda.get_device_name(0)

'NVIDIA GeForce RTX 3060 Ti'

In [4]:
cuda = torch.device('cuda')
cpu = torch.device('cpu')

In [5]:
a = torch.rand(6000, 6000).to(cuda)
b = torch.rand(6000, 6000).to(cuda)

In [6]:
%time c = torch.matmul(a, b)

CPU times: total: 672 ms
Wall time: 724 ms


In [4]:
aa = np.random.rand(6000, 6000)
bb = np.random.rand(6000, 6000)

In [6]:
np.linalg.pinv(np.array(torch.rand(6000, 6000)))

array([[ 3.69891465e-01, -7.51112849e-02,  9.63872224e-02, ...,
         1.88320160e-01,  8.81293863e-02,  5.95068559e-02],
       [ 2.37848327e-01, -8.62966701e-02,  5.69704082e-03, ...,
         1.69915527e-01,  7.41290078e-02,  6.71355501e-02],
       [ 8.31104144e-02, -1.38442377e-02, -5.81950024e-02, ...,
         4.70023677e-02,  3.37803774e-02,  4.44228612e-02],
       ...,
       [-1.91015184e-01,  7.24618137e-03, -4.12276499e-02, ...,
        -9.71592739e-02, -6.05677105e-02, -3.28970738e-02],
       [-1.63057521e-01,  1.01651855e-01, -1.81816399e-01, ...,
         7.03447610e-02,  2.18895846e-04,  3.67377363e-02],
       [ 2.88349122e-01, -7.86762461e-02,  9.45898816e-02, ...,
         1.03111893e-01,  2.80299559e-02,  4.65224497e-02]], dtype=float32)

In [8]:
aa = torch.rand(6000, 6000).to(torch.device('mps'))

In [11]:
torch.matmul(aa, aa)

/Users/scottduanmu/opt/anaconda3/lib/python3.9/site-packages/torch/_tensor_str.py:115: UserWarning: The operator 'aten::nonzero' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1666646981653/work/aten/src/ATen/mps/MPSFallback.mm:11.)
  nonzero_finite_vals = torch.masked_select(


tensor([[1490.1631, 1494.6938, 1495.1478,  ..., 1514.1636, 1490.1755,
         1510.3771],
        [1507.1375, 1502.6964, 1518.1697,  ..., 1522.5254, 1485.6843,
         1509.9264],
        [1492.5540, 1503.4868, 1494.5768,  ..., 1515.1323, 1486.7476,
         1488.3918],
        ...,
        [1496.4347, 1507.3907, 1499.1222,  ..., 1519.9082, 1481.9133,
         1508.2415],
        [1508.6547, 1512.2682, 1516.3824,  ..., 1541.1869, 1503.6816,
         1523.9537],
        [1512.3453, 1518.5709, 1519.3003,  ..., 1535.3820, 1499.0959,
         1524.2950]], device='mps:0')

In [13]:
aa.to('cpu') @ aa.to('cpu')

tensor([[1490.1639, 1494.6946, 1495.1464,  ..., 1514.1603, 1490.1769,
         1510.3784],
        [1507.1409, 1502.6963, 1518.1731,  ..., 1522.5267, 1485.6851,
         1509.9285],
        [1492.5536, 1503.4869, 1494.5785,  ..., 1515.1316, 1486.7473,
         1488.3938],
        ...,
        [1496.4346, 1507.3896, 1499.1213,  ..., 1519.9069, 1481.9120,
         1508.2423],
        [1508.6555, 1512.2651, 1516.3828,  ..., 1541.1864, 1503.6830,
         1523.9536],
        [1512.3447, 1518.5719, 1519.3019,  ..., 1535.3806, 1499.0958,
         1524.2924]])